# Conversion
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: /:categories/:title/

# Setup
# title: "Living life and Make it Better"
# title: "Write it down so that knowledge is not lost"
title: "Make your life more meaningful"
tagline: "Dedicate your life, work and all that you have to the glory of his name."
description: "Learn software development, java programming, android,
  embedded system programming and other open source tehcnology"
logo: /images/dsclogo.jpg
url: https://nicokoibur.github.io

author:
  name: Nico Koibur
  email: nicokoibur@gmail.com
  github: nicokoibur
  linkedin: nicokoiur
  facebook: nico.koibur
  url: http://nicokoibur.github.io
  email_md5: a3c8a6a973fc0c0fa3d89cb69c103ad0
  bio: "Software Developer berdomisili di Jayapura, berkecimpung di lingkungan open source, 
        terutama PHP, Java dan Linux."

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

paginate: 5

# Google Analytics
# google_analytics_tracking_id: UA-36102948-1

# Facebook Comments
facebook_appid: 418147669297621

# Timezone
timezone: Asia/Jayapura
